### PR TITLE
add index.html file

### PR DESCRIPTION
**Pull request by looh16**
Practice project, about all of the tools and best practices, learned in previous steps

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @looh16 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
:heavy_check_mark:  Correct gitflow

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly add a description to the pull request as this helps other coders and reviewers to know what changes you introduced to the milestone,
image

- [ ] Kindly add linter files to your project. [Refer to this link](https://github.com/microverseinc/linters-config/tree/master/html-css)

- [ ] Kindly make your readme file more descriptive. Add information for the section below
image

- [ ] Kindly add a CSS file to your project as this is a requirement for the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by looh16** [comment]
I will follow the recommendations. But to use the same Pull Request submitted for the first review, do I need to close this request first? Thank you!

**Comment by looh16** [comment]
**I have already finished the recommended changes.**

**Review by ishimwezachee — APPROVED** [review]
Hi @looh16 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [x] You have implemented the changes requested by the previous reviewer 

## Optional suggestions

- [OPTIONAL ] Try to give a good descriptive pull request title and when you are writing you pull request summary, i recommend you to add it in bullet format.  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by looh16** [comment]
Thank you!

**Pull request merged**
